apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${_PROJECT_NAME}
  # labels:
  #   last_updated: 1
spec:
  rules:
  # - host: www.shareit.works
    http:
      paths:
      - path: /
        backend:
          serviceName: ${_PROJECT_NAME}
          servicePort: 80