apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${_PROJECT_NAME}
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    certmanager.k8s.io/acme-http01-edit-in-place: "true"
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  # labels:
  #   last_updated: 1
spec:
  backend:
    serviceName: ${_PROJECT_NAME}
    servicePort: 80
  tls:
  - secretName: share-it-secret
    hosts:
    - shareit.works
