kind: Service
apiVersion: v1
metadata:
  name: ${_PROJECT_NAME}
  labels:
    app: ${_PROJECT_NAME}
spec:
  selector:
    app: ${_PROJECT_NAME}
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: ${_CONTAINER_PORT}